# Execute the collection role "run" against all driver-created instances (cleanup / absent)

- name: "Molecule | Cleanup | Include the foundata.dovecot.run role"
  ansible.builtin.include_role:
    name: "foundata.dovecot.run"
  vars:
    run_dovecot_state: "absent"
